name: Slidev Build Steps

on:
  workflow_call:
    inputs:
      output-dir:
        required: true
        type: string

defaults:
  run:
    working-directory: ./slides/src

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output-dir: ${{ inputs.output-dir }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm & dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build Slidev
        run: pnpm build --base / --out ../../${{ inputs.output-dir }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ../../${{ inputs.output-dir }}
