name: Deploy PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]

env:
  DIST_DIR: preview-dist

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-preview:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build-steps.yml
    with:
      output-dir: ${{ env.DIST_DIR }}

  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    needs: build-preview
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.DIST_DIR }}

      - name: Upload PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ${{ env.DIST_DIR }}
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
